name: vonjiaina_front
description: "Vonjiaina - Application de recherche de mÃ©dicaments"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.1.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  url_launcher: ^6.2.2
  intl: ^0.20.2
  logging: ^1.2.0
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  local_auth: ^2.2.0
  encrypt: ^5.0.3
  pointycastle: ^3.7.3
  device_info_plus: ^9.1.1
  google_maps_flutter: ^2.14.0
  dio: ^5.9.0
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
